### ISSUE TITLE
"No log line matching the '' filter"

### ISSUE THREAD

**Issue by nothing2obvi** [Salvoxia/immich-folder-album-creator#76]
This is all I see in the logs. It was working for me before but for some reason this is all I see now. The container may have auto-updated via Watchtower, and I've upgraded to Immich v1.121.0. The API keys are correct. 

My setup:
```
immich-folder-album-creator-user1:
    container_name: immich_folder_albums_user1
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://10.0.0.94:2283/api
      API_KEY: "redacted"
      ROOT_PATH: "/usr/src/app/external"
      ALBUM_LEVELS: 5
      ALBUM_SEPARATOR: " - "
      CRON_EXPRESSION: "00 12 * * *"
      TZ: America/Los_Angeles
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

What should I do? Thanks!

**Comment by Salvoxia** [comment]
Are you managing your containers with portainer?
The message is typical for an empty log file. The container will not log anything until the cronjob runs, so make sure it has been running long enough after updating.

**Comment by nothing2obvi** [comment]
Okay, I'll report back. Thanks!

**Comment by nothing2obvi** [comment]
I know it's not exactly the original issue, but I'm not sure why it's giving an error that it can't connect. It used to connect fine using my original `docker-compose.yml` from above. I also am using the correct API key:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffffb49029c0>: Failed to establish a new connection: [Errno 101] Network unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.0.0.94', port=2283): Max retries exceeded with url: /api/server/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb49029c0>: Failed to establish a new connection: [Errno 101] Network unreachable'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/script/immich_auto_album.py", line 890, in <module>
    version = fetchServerVersion()
              ^^^^^^^^^^^^^^^^^^^^
  File "/script/immich_auto_album.py", line 317, in fetchServerVersion
    r = requests.get(api_endpoint, **requests_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.0.0.94', port=2283): Max retries exceeded with url: /api/server/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb49029c0>: Failed to establish a new connection: [Errno 101] Network unreachable'))
```

**Comment by nothing2obvi** [comment]
Not exactly the same issue, but I'm running 2 containers and only 1 seems to connect and finishes the job.

`docker-compose.yml`
```
immich-folder-album-creator-user1:
    container_name: immich_folder_albums_user1
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://10.0.0.94:2283/api
      API_KEY: "redacted1"
      ROOT_PATH: "/usr/src/app/external"
      ALBUM_LEVELS: 5
      ALBUM_SEPARATOR: " - "
      CRON_EXPRESSION: "00 12 * * *"
      TZ: America/Los_Angeles
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  immich-folder-album-creator-user2:
    container_name: immich_folder_albums_user2
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://10.0.0.94:2283/api
      API_KEY: "redacted2"
      ROOT_PATH: "/usr/src/app/external"
      ALBUM_LEVELS: 5
      ALBUM_SEPARATOR: " - "
      CRON_EXPRESSION: "00 13 * * *"
      TZ: America/Los_Angeles
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

The error that the 2nd container is getting is:
```
Search
k
Hosts
orbstack
immich_folder_albums_dad
salvoxia/immich-folder-album-creator:latest
mem
load
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffffa0c73830>: Failed to establish a new connection: [Errno 101] Network unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.0.0.94', port=2283): Max retries exceeded with url: /api/server/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa0c73830>: Failed to establish a new connection: [Errno 101] Network unreachable'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/script/[immich](http://10.0.0.94:9999/container/40ca32289364)_auto_album.py", line 890, in <module>
    version = fetchServerVersion()
              ^^^^^^^^^^^^^^^^^^^^
  File "/script/immich_auto_album.py", line 317, in fetchServerVersion
    r = requests.get(api_endpoint, **requests_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.0.0.94', port=2283): Max retries exceeded with url: /api/server/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa0c73830>: Failed to establish a new connection: [Errno 101] Network unreachable'))
close
close
```

I've even tried giving it a brand new API key, and it doesn't work. Not sure what I'm doing wrong.

**Comment by Salvoxia** [comment]
Both containers using the same `API_URL` but only one reporting "Network unreachable" doesn't make too much sense to me.
Is  `10.0.0.94` the IP of your Docker host or the IP of the Immich container in the Docker bridge network? If it's the Docker host's IP, I suggest switching to the Immich container name, assuming you're running the container in the Immich compose file along with the other Immich containers.
You can also try attaching to the container throwing the error and running
`./immich_auto.album.sh`
manually to check if it works in general and the error was just thrown because the cronjob ran at an unfortunate time.

**Comment by nothing2obvi** [comment]
So, I changed the `10.0.0.94` to `immich_server`, I ran `/script/immich_auto_album.sh` in Container1 and it worked, ending with:

```
Check that this is the list of albums you want to create. Run the container with environment variable UNATTENDED set to 1 to actually create these albums.

For Container2, I get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 206, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0xffff7fb46480>: Failed to resolve 'immich_server' ([Errno -3] Try again)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='immich_server', port=2283): Max retries exceeded with url: /api/server/version (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff7fb46480>: Failed to resolve 'immich_server' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/script/immich_auto_album.py", line 890, in <module>
    version = fetchServerVersion()
              ^^^^^^^^^^^^^^^^^^^^
  File "/script/immich_auto_album.py", line 317, in fetchServerVersion
    r = requests.get(api_endpoint, **requests_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='immich_server', port=2283): Max retries exceeded with url: /api/server/version (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffff7fb46480>: Failed to resolve 'immich_server' ([Errno -3] Try again)"))
```

I then ran `docker compose down && docker compose up -d --force-recreate` and now the containers have switched. Container2 runs and Container1 has the error. I ran `docker inspect` on both to see that the address and API keys are correct.

Some kind of weird Docker thing going on?

**Comment by nothing2obvi** [comment]
Figured it out. Had to put them in their own separate `docker-compose.yml` file, not using the external network settings I had in my main Immich `docker-compose.yml` file, and use `10.0.0.94` instead of `immich_server`.

Thanks for your help!
